version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - '5432:5432'
    restart: on-failure

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend:delegated
      - /app/backend/node_modules
    ports:
      - '3001:3001'
      - '5555:5555'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend:delegated
      - /app/frontend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
      - nginx
    env_file:
      - .env
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./trans.conf:/etc/nginx/conf.d/trans.conf
    ports:
      - '8080:8080'
    restart: on-failure

volumes:
  postgres_data:
