FROM node:18-alpine3.17

RUN rm -rf /app/backend/prisma/migrations

WORKDIR /app/backend/
COPY . /app/backend/

RUN npm install

RUN rm -rf ./prisma/migrations

CMD ["npm", "run", "start:migrate:dev"]
