FROM node:18-alpine3.17

WORKDIR /app/backend/
COPY . /app/backend/

RUN npm install

RUN rm -rf backend/prisma/migrations
COPY startDB.sh /app/backend/

# CMD ["npm", "run", "start:dev"]

ENTRYPOINT ["sh", "/app/backend/startDB.sh"]